apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-ui
  labels:
    app: bookshop-ui

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop-ui
  template:
    metadata:
      labels:
        app: bookshop-ui
    spec:
      containers:
        - name: bookshop-ui
          image: bookshop-ui
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8001
