apiVersion: v1
kind: Service
metadata:
  name: bookshop-ui
  labels:
    app: bookshop-ui
spec:
  type: ClusterIP
  selector:
    app: bookshop-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001

